language: node_js
node_js:
  - "6.11"
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
notifications:
  email:
    on_failure: always
branches:
  only:
  - master
