language: node_js
node_js:
- '6.11'
sudo: false
addons:
  ssh_known_hosts: 146.185.145.169
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_62364ec7289b_key -iv $encrypted_62364ec7289b_iv
  -in ci/deploy_rsa.enc -out tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- npm install
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -rtgoP --quiet $TRAVIS_BUILD_DIR/ ci@146.185.145.169:$BUILD_PATH
  on:
    branch: master
after_deploy: ssh-agent -k
notifications:
  email:
    on_failure: always
branches:
  only:
  - master
